[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
program-b = "4BtDbdzhLtz5AU4qgcse2WVq9eSDHGqCwRQFubqku63X"
program-c = "7vc3k64pE9wkxkmhNiK7HRyC7ymhPd9UBzuD11gtaWiQ"
program_a = "4VGfDBA9bzNQePeb5CHG3XMbBMuWXozKJF5uAWH6asue"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-local = "solana program deploy target/deploy/program_c.so --program-id target/deploy/program_c.json -C ~/.config/solana/cli/local.yml --use-rpc --with-compute-unit-price 10"
